AWSTemplateFormatVersion: 2010-09-09
Description: 'IaC Immersion Day - CI/CD Pipeline'
Parameters:
  YourName:
    Description: Your name.
    Type: String
  RoleArn:
    Description: IAM Role ARN for CodePipeline
    Type: String
Resources:
  Repository:
    Type: 'AWS::CodeCommit::Repository'
    Properties:
      RepositoryName: !Ref YourName
      RepositoryDescription: CodeCommit Repository
  Artifacts:
    Type: AWS::S3::Bucket
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Join
        - ''
        - - !GetAtt [Repository, Name]
          - -pipeline
      ArtifactStore:
        Type: S3
        Location:
          Ref: Artifacts
      RoleArn: !Ref RoleArn
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: CheckoutSourceTemplate
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Configuration:
                PollForSourceChanges: True
                RepositoryName: !GetAtt [Repository, Name]
                BranchName: master
              OutputArtifacts:
                - Name: TemplateSource
              RunOrder: 1
        -
          Name: Deploy
          Actions:
            -
              Name: CreateStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !Ref RoleArn
                StackName: !Join
                  - ''
                  - - !GetAtt [Repository, Name]
                    - -deploy-stack
                Capabilities: CAPABILITY_IAM
                TemplatePath: TemplateSource::template.yml
                TemplateConfiguration: TemplateSource::parameters.json
              RunOrder: 1
        -
          Name: Approve
          Actions:
            -
              Name: ApproveStack
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              RunOrder: 1
        -
          Name: Delete
          Actions:
            -
              Name: DeleteStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: DELETE_ONLY
                RoleArn: !Ref RoleArn
                StackName: !Join
                  - ''
                  - - !GetAtt [Repository, Name]
                    - -deploy-stack
                Capabilities: CAPABILITY_IAM
                TemplatePath: TemplateSource::template.yml
                TemplateConfiguration: TemplateSource::parameters.json
              RunOrder: 1
Outputs:
  CloneUrlHttp:
    Value: !GetAtt
      - Repository
      - CloneUrlHttp
  CodeCommitURL:
    Value: !Join
      - ''
      - - 'https://console.aws.amazon.com/codecommit/home?region='
        - !Ref 'AWS::Region'
        - '#/repository/'
        - !Ref 'AWS::StackName'
        - /browse/HEAD/--/
    Description: Git Repository URL
