AWSTemplateFormatVersion: 2010-09-09
Description: ''
Parameters:
  YourName:
    Description: Your name.
    Type: String
Resources:
  Repository:
    Type: 'AWS::CodeCommit::Repository'
    Properties:
      RepositoryName: !Ref YourName
      RepositoryDescription: CodeCommit Repository
  Artifacts:
    Type: AWS::S3::Bucket
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudPipelinePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "cloudformation:*"
                Resource: "*"
              - Effect: Allow
                Action: "codecommit:*"
                Resource: "*"
              - Effect: Allow
                Action: "s3:*"
                Resource: "*"
              - Effect: Allow
                Action: "sns:*"
                Resource: "*"
              - Effect: Allow
                Action: "ec2:*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "*"
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Join
        - ''
        - - !GetAtt [Repository, Name]
          - -pipeline
      ArtifactStore:
        Type: S3
        Location:
          Ref: Artifacts
      RoleArn: !GetAtt [PipelineRole, Arn]
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: CheckoutSourceTemplate
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Configuration:
                PollForSourceChanges: True
                RepositoryName: !GetAtt [Repository, Name]
                BranchName: master
              OutputArtifacts:
                - Name: TemplateSource
              RunOrder: 1
        -
          Name: Deploy
          Actions:
            -
              Name: CreateStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt [PipelineRole, Arn]
                StackName: !Join
                  - ''
                  - - !GetAtt [Repository, Name]
                    - -deploy-stack
                Capabilities: CAPABILITY_IAM
                TemplatePath: TemplateSource::template.yml
                TemplateConfiguration: TemplateSource::parameters.json
              RunOrder: 1
Outputs:
  CloneUrlHttp:
    Value: !GetAtt
      - Repository
      - CloneUrlHttp
  CodeCommitURL:
    Value: !Join
      - ''
      - - 'https://console.aws.amazon.com/codecommit/home?region='
        - !Ref 'AWS::Region'
        - '#/repository/'
        - !Ref 'AWS::StackName'
        - /browse/HEAD/--/
    Description: Git Repository URL
