AWSTemplateFormatVersion: 2010-09-09
Description: ''
Parameters:
  YourName:
    Description: Your name.
    Type: String
  VPCName:
    Description: Name of the VPC
    Type: String
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.40.144.0/20
      EnableDnsSupport: False
      EnableDnsHostnames: False
      Tags:
        -
          Key: "Name"
          Value: !Join
            - ''
            - - !Ref VPCName
              - " VPC"
        -
          Key: "creator"
          Value: "CloudFormation"
  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.40.144.0/20
      MapPublicIpOnLaunch: False
      VpcId: !Ref VPC
      Tags:
        -
          Key: "Name"
          Value: "Private Subnet A"
        -
          Key: "creator"
          Value: "CloudFormation"
  ElasticIP:
  NATGateway:
  RouteTable:
  AmazonLinux:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-02e680c4540db351e"
      InstanceType: "t2.micro"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          sudo yum install stress -y
          echo '*/10 * * * * stress --cpu 1 --timeout 300' > /tmp/stress_cron.txt
          sudo -u ec2-user bash -c 'crontab /tmp/stress_cron.txt'
      SubnetId: !Ref PrivateSubnetA
      Tags:
        -
          Key: "Name"
          Value: !Join
            - ''
            - - "Amazon Linux for "
              - !Ref YourName
        -
          Key: "creator"
          Value: "CloudFormation"
