AWSTemplateFormatVersion: 2010-09-09
Description: 'IaC Immersion Day - VPC, Subnet'
Parameters:
  VPCName:
    Description: Name of the VPC
    Type: String
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.40.144.0/20
      EnableDnsSupport: False
      EnableDnsHostnames: False
      Tags:
        -
          Key: "Name"
          Value: !Join
            - ''
            - - !Ref VPCName
              - " VPC"
        -
          Key: "creator"
          Value: "CloudFormation"
  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.40.144.0/20
      MapPublicIpOnLaunch: False
      VpcId: !Ref VPC
      Tags:
        -
          Key: "Name"
          Value: "Private Subnet A"
        -
          Key: "creator"
          Value: "CloudFormation"
Outputs:
  SubnetId:
    Value: !Ref PrivateSubnetA
